version: '3.4'

services:
  signature.webapi:
    image: ${DOCKER_REGISTRY-}signaturewebapi
    build:
      context: .
      dockerfile: Signature.WebAPI/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"
  signature.cache:
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"

