// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignaturePersistance;

#nullable disable

namespace SignaturePersistance.Migrations
{
    [DbContext(typeof(SignatureDbContext))]
    partial class SignatureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SignatureDomain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentary")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("SignedBy")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasMaxLength(1024)
                        .HasColumnType("int");

                    b.Property<int>("Stauts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SignatureDomain.Entities.SignatureFilesToUsers", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("SignatureFilesToUsers");
                });

            modelBuilder.Entity("SignatureDomain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IDNP")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89990cf6-e9d9-49c5-a86d-199e815a7739"),
                            Address = "Planet Earth",
                            CreateDate = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(5866),
                            DateOfBirth = new DateTime(2024, 4, 17, 21, 36, 52, 438, DateTimeKind.Local).AddTicks(5819),
                            Email = "admin@lvbgroup.com",
                            FirstName = "First",
                            Gender = 0,
                            IDNP = "0000000000001",
                            LastModified = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(6415),
                            LastName = "User",
                            Password = "c1c224b03cd9bc7b6a86d77f5dace40191766c485cd55dc48caf9ac873335d6f",
                            PhoneNumber = "69000001",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c025a8b3-4fab-45d8-86c7-aaa506b77270"),
                            Address = "Planet Earth",
                            CreateDate = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(7498),
                            DateOfBirth = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(7492),
                            Email = "user@lvbgroup.com",
                            FirstName = "Second",
                            Gender = 0,
                            IDNP = "0000000000002",
                            LastModified = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(7499),
                            LastName = "User",
                            Password = "b512d97e7cbf97c273e4db073bbb547aa65a84589227f8f3d9e4a72b9372a24d",
                            PhoneNumber = "69000002",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("743be124-595f-4880-a2db-d657e5dd86c2"),
                            Address = "Planet Earth",
                            CreateDate = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(7530),
                            DateOfBirth = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(7528),
                            Email = "user@lvbgroup.com",
                            FirstName = "Third",
                            Gender = 0,
                            IDNP = "0000000000003",
                            LastModified = new DateTime(2024, 4, 17, 21, 36, 52, 439, DateTimeKind.Local).AddTicks(7532),
                            LastName = "User",
                            Password = "b512d97e7cbf97c273e4db073bbb547aa65a84589227f8f3d9e4a72b9372a24d",
                            PhoneNumber = "69000003",
                            Status = 1
                        });
                });

            modelBuilder.Entity("SignatureDomain.Entities.SignatureFilesToUsers", b =>
                {
                    b.HasOne("SignatureDomain.Entities.File", "File")
                        .WithMany("SignatureFilesToUsers")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SignatureDomain.Entities.User", "User")
                        .WithMany("SignatureFilesToUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SignatureDomain.Entities.File", b =>
                {
                    b.Navigation("SignatureFilesToUsers");
                });

            modelBuilder.Entity("SignatureDomain.Entities.User", b =>
                {
                    b.Navigation("SignatureFilesToUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
